API Key: TEST
Max Token Usage: 990
Exchange Codes:
  US:
    Exchanges:
    - NYSE
    - NASDAQ
    - AMEX
    Symbol Type:
    - Common Stock
    - ETF
Purge Data:
- Logs
- Actions
- Imports
Data Retention:
  Critical: 1 year
  Debug: 2 weeks
  Error: 1 year
  Information: 3 months
  Trace: 1 week
  Warning: 6 months
On Empty Database:
- Priority: 1
  Scope: Full
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
Any Day:
- Priority: 1
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
Sunday:
- Skip: true
Monday:
- Skip: true
Tuesday:
- Priority: 1
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
Wednesday:
- Priority: 1
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
Thursday:
- Priority: 1
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
Friday:
- Priority: 1
  Skip: false
  Scope: Bulk
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
Saturday:
- Priority: 1
  Scope: Full
  Data Types:
  - Symbols
  - Prices
  - Options
  - Dividends
  - Splits
- Priority: 2
  Scope: Full
  Data Types:
  - Fundamentals
